{% set version = "1.9.0" %}

package:
  name: robotframework-robocop
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/r/robotframework-robocop/robotframework-robocop-{{ version }}.tar.gz
    sha256: 71fe062e687ef655aa88dfe389458337f1efb4c0aa0427f68107b9f6a14f2afe
  - folder: src
    url: https://github.com/MarketSquare/robotframework-robocop/archive/refs/tags/{{ version }}.tar.gz
    sha256: c7021a8c54246710c85f5ee1d7fc184a7463385ead61e633dce145a113575807
    patches:
      - 0001-skip-git-test.patch

build:
  number: 0
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv
  entry_points:
    - robocop=robocop:run_robocop

requirements:
  host:
    - pip
    - python >=3.6
    - robotframework >=3.2.2
  run:
    - python >=3.6
    - robotframework >=3.2.2

test:
  source_files:
    - src/tests
  imports:
    - robocop
  commands:
    - pip check
    - robocop --version
    - robocop --help
    - cd src
    - coverage run --source=robocop -m pytest
    - coverage report --fail-under=96
  requires:
    - coverage
    - pip
    - pytest
    - toml

about:
  home: https://github.com/MarketSquare/robotframework-robocop
  summary: Static code analysis tool (linter) for Robot Framework
  license: Apache-2.0
  license_file: src/LICENSE
  doc_url: https://robocop.readthedocs.io
  description: |
    Robocop is a tool that performs static code analysis of Robot Framework code.

    It uses official Robot Framework parsing API to parse files and run number of
    checks, looking for potential errors or violations to code quality standards.

extra:
  recipe-maintainers:
    - bollwyvl
